### ISSUE TITLE
JavaScript Engine for Alt-Condition Evaluation

### ISSUE THREAD

**Issue by stefan-grafberger** [FionaGuerin/plantestic#94]
Wir könnten auch einfach Javascript Code in der condition evaluieren :lächeln:
Wäre aus Endanwendersicht bestimmt ziemlich nice.
Also quasi:
- string 1:1 in die condition einfügen
- zur runtime dann templating
- den resultierenden string dann als Javascript interpretieren und evaluieren

Aufwand: 30min
Niceigkeit: glaube gar nicht soooo schlimm, auch wenn der generierte Code im acceleo dann schrecklich aussieht (ist aber ja nur generierte Code)

Link dazu: https://stackoverflow.com/questions/10917878/evaluate-string-as-a-condition-java

**Comment by MichelleMar** [comment]
Isn't this already done with Issue #86 ?
